dfs:
  url: 192.168.244.10:8181
druid:
  url: jdbc:mysql://119.3.30.5:3307/mask?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  minPoolSize: 2
  maxPoolSize: 10
  maxIdleTime: 1800000
  acquireIncrement: 3
  maxStatements: 1000
  initialPoolSize: 3
  idleConnectionTestPeriod: 30
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: true
  testConnectionOnCheckin: true
zookeeper:
  url: zookeeper://119.3.30.5:2181 #114.115.171.119

mybatis:
  mapper-locations: classpath*:mapping/**/*.xml
  config-location: classpath:SqlMapConfig.xml
spring:
  sleuth:
    sampler:
      percentage: 1.0
    web:
      client:
        enabled: true
  application:
    name: mask-user-service
  redis:
    host: 42.192.182.126
    port: 6379
    password: 1659868245
  data:
    mongodb:
      uri: mongodb://42.192.182.126:27017/mask
  datasource:
    initialization-mode: always
  zipkin:
    base-url: http://119.3.30.5:9411/
    sender:
      type: kafka
  kafka:
    bootstrap-servers: 119.3.30.5:9092

dubbo:
  application:
    name: mask-nacos
    parameters:
      namespace: dev
      group: mask-nacos
  registry:
    address: nacos://:42.192.182.126:8848
  protocol:
    name: dubbo
    port: 20880

nacos:
  discovery:
    server-addr: 42.192.182.126:8848
    namespace: dev
    register:
      group-name: mask-nacos
      service-name: mask-nacos
    auto-register: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@42.192.182.126:8763/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 1000
  ReadTimeout: 5000
  OkToRetryOnAllOperations: false
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0

wx:
  app-id: wxd2bf68f18c88352a
  app-secret: 6121b5aeca6adb9df720f8618bfd0d5b
  redirect-uri: https://mask.cn
  mchId: xxxxxxxx
  key: xxxxxxxx
  certPath:
  notify_url: http://thesunbig.imwork.net/wx/notify
  wap_url: https://pay.qq.com
  spbill_create_ip: 127.0.0.1

logging:
  level:
    root: info
    cn:
      enjoy:
        users:
          dao: debug
    org:
      springframework:
        cloud:
          sleuth: debug