dfs:
  url: 192.168.244.10:8181
druid:
  url: jdbc:mysql://119.3.30.5:3307/mask?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  minPoolSize: 2
  maxPoolSize: 10
  maxIdleTime: 1800000
  acquireIncrement: 3
  maxStatements: 1000
  initialPoolSize: 3
  idleConnectionTestPeriod: 30
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: true
  testConnectionOnCheckin: true
zookeeper:
  url: zookeeper://119.3.30.5:2181 #114.115.171.119

mybatis:
  mapper-locations: classpath*:mapping/*.xml
  config-location: classpath:SqlMapConfig.xml
spring:
  application:
    name: mask-user-service
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        server-addr: 42.192.182.126:8848
        namespace: 86381884-86d1-481e-8c08-c92d6ef1e80e
        group: dev
    sentinel:
      transport:
        dashboard: 42.192.182.126:8858
      eager: true
      web-context-unify: true
  redis:
    host: 42.192.182.126
    port: 6379
    password: 1659868245
  zipkin:
    base-url: http://119.3.30.5:9411/
    sender:
      type: kafka
  kafka:
    bootstrap-servers: 119.3.30.5:9092

dubbo:
  scan:
    base-packages: cn.mask.mask.user.dubbo
  protocol:
    name: dubbo
    port: 28080
  registry:
    address: spring-cloud://42.192.182.126
csp:
  sentinel:
    dashboard:
      server: 42.192.182.126:8858

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    diskspace:
      enabeld: false

wx:
  app-id: wxd2bf68f18c88352a
  app-secret: 6121b5aeca6adb9df720f8618bfd0d5b
  redirect-uri: https://mask.cn
  mchId: xxxxxxxx
  key: xxxxxxxx
  certPath:
  notify_url: http://thesunbig.imwork.net/wx/notify
  wap_url: https://pay.qq.com
  spbill_create_ip: 127.0.0.1

logging:
  level:
    root: info
    cn:
      enjoy:
        users:
          dao: debug
    org:
      springframework:
        cloud:
          sleuth: debug